### ISSUE TITLE
`vpc` MVP

### ISSUE THREAD

**Issue by sean-** [joyent/freebsd-vpc#10]
- [ ] `vpc vtep` subcommand - joyent/freebsd-vpc#12
- [ ] `vpc vm create` - joyent/freebsd-vpc#27
- [ ] `vpc vm run` - joyent/freebsd-vpc#28
- [ ] `vpc vm destroy` - joyent/freebsd-vpc#29
- [ ] `vpc vtep dump` - debugging aid
- [ ] `vpc vm list`
- [ ] `vmnic list` - already possible with `vpc list -t vmnic`, wtb symmetric UX
- [ ] `vpcsw get` using info from `vpc_ctl(2)`
- [ ] `vmnic set` option: `mac` - currently inferred from VPC ID
- [ ] `vmnic set` option: `mtu` - defaults to 1500
- [ ] `port connect` interface - not currently expoesd
- [ ] `vpc vm list` - wtb package that handles state of individual bhyve VMs
- [ ] `vpc vm get`
- [ ] `vpc account list` - list VNIs for each account
- [ ] `vpc account destroy`
- [ ] `vpc subnet create` - Adds a subnet to a `vpcsw`
- [ ] `vpc subnet list` - Lists subnets on a given `vpcsw`
- [ ] `vpc subnet destroy` - Removes a given subnet
- [X] `vpc mux` subcommand - joyent/freebsd-vpc#41
- [X] `vpc hostlink` subcommand - joyent/freebsd-vpc#40

There are more, but this was the identified critical path.
